<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">

        <title>Python for Science</title>

        <meta name="author" content="pyHPC Team">

        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">


        <link rel="stylesheet" href="css/reveal.css">
        <link rel="stylesheet" href="css/theme/serif.css" id="theme">

        <!-- For syntax highlighting -->
        <link rel="stylesheet" href="lib/css/xcode.css">

        <!-- If the query includes 'print-pdf', use the PDF print sheet -->
        <script>
            document.write( '<link rel="stylesheet" href="css/print/' + ( window.location.search.match( /print-pdf/gi ) ? 'pdf' : 'paper' ) + '.css" type="text/css" media="print">' );
        </script>

        <!--[if lt IE 9]>
        <script src="lib/js/html5shiv.js"></script>
        <![endif]-->

        <style type="text/css">
            ul { margin-bottom: 25px; }
            li li { list-style: circle; }
        </style>

    </head>
    <body>
